name: Set Gsd By Shell

on:
  workflow_dispatch: # 手动运行
  watch:
    types: [ started ] # 点 star 触发运行
  #schedule:
    #- cron: '*/30 * * * *' # 每隔 30 分钟运行
  push:
    branches: [ master ] # 推送 master 分支时运行
    paths-ignore: # 下列文件的变更不触发部署
      - README.md
      - LICENSE
  #pull_request:
    #branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Gsd
    steps:
    - name: Checkout master
      uses: actions/checkout@v3

    - name: Install jq
      run: |
        if ! type jq &>/dev/null; then
          sudo apt-get install -y jq
        fi

    - name: Do it
      shell: bash
      env:
        API_URL: ${{ secrets.API_URL }}
        API_URL_CHB: ${{ secrets.API_URL_CHB }}
      run: |
        bash github.git.sh

    #- name: Push changes
    #  uses: ad-m/github-push-action@master
    #  with:
    #    github_token: ${{ secrets.GITHUB_TOKEN_LOM }}
